### ISSUE TITLE
what value should we set for `params$gridsize` and why?

### ISSUE THREAD

**Issue by liamxg** [Taming-the-BEAST/Skyline-plots#12]
Dear @laduplessis,

What value should we set for `params$gridsize` and why? Thanks.

**Comment by laduplessis** [comment]
params$gridsize is the resolution you want to plot the Skyline on. The value very much depends on your dataset. For the HCV example, which stretches over about 400 years we set it to 100, so we get a posterior estimate for around every 4th year. Depending on your dataset you may want to get a daily or a weekly estimate. You usually want to set the grid size to be at least as high as the dimension of your skyline plot, but not too much higher.

**Comment by liamxg** [comment]
Dear @laduplessis,
Thanks, got it.
