### ISSUE TITLE
unequal sample size in beast

### ISSUE THREAD

**Issue by doresannie** [Taming-the-BEAST/Skyline-plots#7]
I have 800 isolates of HCV virus isolation year range from 2004 to 2018, for that I am analysing Bayesian skyline plot. For some years I have 100 sequences and for some years I have only 10 sequences. Will II have to keep sample size for each year same or it may different. Will it create any sample size bias in BSP plot? Kindly guide me.

data looks like this; Can I use it?

2018(10 strains),

2017(51),

2016(45),

2015(175),

2014(89),

2013(18),

2012(49),

2011(70),

2010(88),

2009(200),

2008(6),

2007(9)

**Comment by laduplessis** [comment]
It shouldn't create any issues since the BSP conditions on the sample times. 

This is a forum for issues directly related to the tutorial **only** and **not** an open forum for advice on analysing your own datasets.
